#
# Set TOPDIR to the project toplevel directory
# 
TOPDIR = ../..

#
# Include this first, right after setting TOPDIR
#
include $(TOPDIR)/Preamble.make


#
# Add any directories to recurse into via the SUBDIRS variable.
# 
SUBDIRS = 

HEADERS =		\
	osmabi.h	\
	asmdisk.h	\
	asmkernel.h	\
	asmcompat32.h
DIST_FILES = $(HEADERS)


#
# Include this at the very end of the Makefile
#
include $(TOPDIR)/Postamble.make
